theme: jekyll-theme-minimal
title: cnl2asp: Controlled Natural Language to Answer Set Programming
description: A tool for converting English Sentences expressed in a Controlled Natural Language into Answer Set Programming rules
